version: '3.9'  
services:
  django:
    container_name: Public
    image: django-docker:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.front  
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: python3 manage.py runserver 0.0.0.0:8000

  api:
    container_name: Api
    image: django-api-docker:0.0.1  
    build:
      context: .
      dockerfile: Dockerfile.api  
    ports:
      - "8001:8001"  
    volumes:
      - .:/code
    command: python3 manage.py runserver 0.0.0.0:8001

  db:
    container_name: Db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db.sqlite3  # Nom de la base de données
      POSTGRES_USER: myuser     # Nom d'utilisateur
      POSTGRES_PASSWORD: mypassword # Mot de passe
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nginx:
    container_name: nginx2
    image: nginx
    ports:
      - "80:80"
   
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/access.log:/var/log/nginx/access.log

volumes:
  postgres_data: {}
    
