# Generated by Django 5.1 on 2024-09-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pokemon_remove_choice_question_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
