# Generated by Django 5.1.1 on 2024-09-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(default='pikachu.jpg', upload_to='photos'),
            preserve_default=False,
        ),
    ]
