# Generated by Django 5.1.1 on 2024-09-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_pokemon_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
